// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBbOnsI-y-mld5VJjwiPUF5cDUYbM8E8g',
    appId: '1:681375372465:web:07b776d5ac4f169871fe90',
    messagingSenderId: '681375372465',
    projectId: 'recruit-duck',
    authDomain: 'recruit-duck.firebaseapp.com',
    storageBucket: 'recruit-duck.appspot.com',
    measurementId: 'G-Q80HYL87V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3LJtVyb7ItywsUmvN6qUsBH4hU6bLZQ',
    appId: '1:681375372465:android:f1636fa511a0b28571fe90',
    messagingSenderId: '681375372465',
    projectId: 'recruit-duck',
    storageBucket: 'recruit-duck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxOb6WbxosZY7qNHR_Uw-G9FxZ1b_Gt7Q',
    appId: '1:681375372465:ios:3aeeeabed7f639ff71fe90',
    messagingSenderId: '681375372465',
    projectId: 'recruit-duck',
    storageBucket: 'recruit-duck.appspot.com',
    iosClientId: '681375372465-1cje05eir8a0nr558q73rcd7dp5io0r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobFinderApp',
  );
}
